### ISSUE TITLE
Main.java uses non-static main method

### ISSUE THREAD

**Issue by Zenneo** [Zenneo/leJOS_NXT_programs#8]
Using Eclipse all functions and variables of the Main.java should be changed to static to solve following compilation error:
```
js.tinyvm.TinyVMException: main method not found, program has no entry point
	at js.tinyvm.Binary.markUsed(Binary.java:579)
	at js.tinyvm.Binary.createFromClosureOf(Binary.java:316)
	at js.tinyvm.TinyVMTool.link(TinyVMTool.java:97)
	at js.tinyvm.TinyVMTool.link(TinyVMTool.java:48)
	at lejos.pc.tools.NXJLink.start(NXJLink.java:134)
	at lejos.pc.tools.NXJLink.run(NXJLink.java:101)
	at lejos.pc.tools.NXJLink.start(NXJLink.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at lejos.pc.tools.ToolStarter.startTool(ToolStarter.java:31)
	at lejos.pc.tools.NXJLink.main(NXJLink.java:28)
```

**Comment by Zenneo** [comment]
Solved by f7fffd6bf47e1d6fc29b84fca6170f791e361831
